// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "niemb.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace nc {
namespace niemb {

namespace {

const ::google::protobuf::Descriptor* User1Data_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  User1Data_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_niemb_2eproto() {
  protobuf_AddDesc_niemb_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "niemb.proto");
  GOOGLE_CHECK(file != NULL);
  User1Data_descriptor_ = file->message_type(0);
  static const int User1Data_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(User1Data, switch__),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(User1Data, led_),
  };
  User1Data_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      User1Data_descriptor_,
      User1Data::default_instance_,
      User1Data_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(User1Data, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(User1Data, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(User1Data));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_niemb_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    User1Data_descriptor_, &User1Data::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_niemb_2eproto() {
  delete User1Data::default_instance_;
  delete User1Data_reflection_;
}

void protobuf_AddDesc_niemb_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013niemb.proto\022\010nc.niemb\"(\n\tUser1Data\022\016\n\006"
    "switch\030\001 \001(\010\022\013\n\003led\030\002 \001(\010", 65);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "niemb.proto", &protobuf_RegisterTypes);
  User1Data::default_instance_ = new User1Data();
  User1Data::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_niemb_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_niemb_2eproto {
  StaticDescriptorInitializer_niemb_2eproto() {
    protobuf_AddDesc_niemb_2eproto();
  }
} static_descriptor_initializer_niemb_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int User1Data::kSwitchFieldNumber;
const int User1Data::kLedFieldNumber;
#endif  // !_MSC_VER

User1Data::User1Data()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void User1Data::InitAsDefaultInstance() {
}

User1Data::User1Data(const User1Data& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void User1Data::SharedCtor() {
  _cached_size_ = 0;
  switch__ = false;
  led_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

User1Data::~User1Data() {
  SharedDtor();
}

void User1Data::SharedDtor() {
  if (this != default_instance_) {
  }
}

void User1Data::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* User1Data::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return User1Data_descriptor_;
}

const User1Data& User1Data::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_niemb_2eproto();  return *default_instance_;
}

User1Data* User1Data::default_instance_ = NULL;

User1Data* User1Data::New() const {
  return new User1Data;
}

void User1Data::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    switch__ = false;
    led_ = false;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool User1Data::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bool switch = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &switch__)));
          set_has_switch_();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_led;
        break;
      }
      
      // optional bool led = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_led:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &led_)));
          set_has_led();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void User1Data::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional bool switch = 1;
  if (has_switch_()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->switch_(), output);
  }
  
  // optional bool led = 2;
  if (has_led()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->led(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* User1Data::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional bool switch = 1;
  if (has_switch_()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->switch_(), target);
  }
  
  // optional bool led = 2;
  if (has_led()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->led(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int User1Data::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional bool switch = 1;
    if (has_switch_()) {
      total_size += 1 + 1;
    }
    
    // optional bool led = 2;
    if (has_led()) {
      total_size += 1 + 1;
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void User1Data::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const User1Data* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const User1Data*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void User1Data::MergeFrom(const User1Data& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_switch_()) {
      set_switch_(from.switch_());
    }
    if (from.has_led()) {
      set_led(from.led());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void User1Data::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void User1Data::CopyFrom(const User1Data& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool User1Data::IsInitialized() const {
  
  return true;
}

void User1Data::Swap(User1Data* other) {
  if (other != this) {
    std::swap(switch__, other->switch__);
    std::swap(led_, other->led_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata User1Data::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = User1Data_descriptor_;
  metadata.reflection = User1Data_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace niemb
}  // namespace nc

// @@protoc_insertion_point(global_scope)
