// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: niemb.proto

package nc.niemb;

public final class Niemb {
  private Niemb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface User1DataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional bool switch = 1;
    boolean hasSwitch();
    boolean getSwitch();
    
    // optional bool led = 2;
    boolean hasLed();
    boolean getLed();
  }
  public static final class User1Data extends
      com.google.protobuf.GeneratedMessage
      implements User1DataOrBuilder {
    // Use User1Data.newBuilder() to construct.
    private User1Data(Builder builder) {
      super(builder);
    }
    private User1Data(boolean noInit) {}
    
    private static final User1Data defaultInstance;
    public static User1Data getDefaultInstance() {
      return defaultInstance;
    }
    
    public User1Data getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nc.niemb.Niemb.internal_static_nc_niemb_User1Data_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nc.niemb.Niemb.internal_static_nc_niemb_User1Data_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional bool switch = 1;
    public static final int SWITCH_FIELD_NUMBER = 1;
    private boolean switch_;
    public boolean hasSwitch() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public boolean getSwitch() {
      return switch_;
    }
    
    // optional bool led = 2;
    public static final int LED_FIELD_NUMBER = 2;
    private boolean led_;
    public boolean hasLed() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public boolean getLed() {
      return led_;
    }
    
    private void initFields() {
      switch_ = false;
      led_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, switch_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, led_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, switch_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, led_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static nc.niemb.Niemb.User1Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static nc.niemb.Niemb.User1Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static nc.niemb.Niemb.User1Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static nc.niemb.Niemb.User1Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static nc.niemb.Niemb.User1Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static nc.niemb.Niemb.User1Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static nc.niemb.Niemb.User1Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static nc.niemb.Niemb.User1Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static nc.niemb.Niemb.User1Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static nc.niemb.Niemb.User1Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(nc.niemb.Niemb.User1Data prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements nc.niemb.Niemb.User1DataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nc.niemb.Niemb.internal_static_nc_niemb_User1Data_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nc.niemb.Niemb.internal_static_nc_niemb_User1Data_fieldAccessorTable;
      }
      
      // Construct using nc.niemb.Niemb.User1Data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        switch_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        led_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nc.niemb.Niemb.User1Data.getDescriptor();
      }
      
      public nc.niemb.Niemb.User1Data getDefaultInstanceForType() {
        return nc.niemb.Niemb.User1Data.getDefaultInstance();
      }
      
      public nc.niemb.Niemb.User1Data build() {
        nc.niemb.Niemb.User1Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private nc.niemb.Niemb.User1Data buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        nc.niemb.Niemb.User1Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public nc.niemb.Niemb.User1Data buildPartial() {
        nc.niemb.Niemb.User1Data result = new nc.niemb.Niemb.User1Data(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.switch_ = switch_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.led_ = led_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nc.niemb.Niemb.User1Data) {
          return mergeFrom((nc.niemb.Niemb.User1Data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(nc.niemb.Niemb.User1Data other) {
        if (other == nc.niemb.Niemb.User1Data.getDefaultInstance()) return this;
        if (other.hasSwitch()) {
          setSwitch(other.getSwitch());
        }
        if (other.hasLed()) {
          setLed(other.getLed());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              switch_ = input.readBool();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              led_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional bool switch = 1;
      private boolean switch_ ;
      public boolean hasSwitch() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public boolean getSwitch() {
        return switch_;
      }
      public Builder setSwitch(boolean value) {
        bitField0_ |= 0x00000001;
        switch_ = value;
        onChanged();
        return this;
      }
      public Builder clearSwitch() {
        bitField0_ = (bitField0_ & ~0x00000001);
        switch_ = false;
        onChanged();
        return this;
      }
      
      // optional bool led = 2;
      private boolean led_ ;
      public boolean hasLed() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public boolean getLed() {
        return led_;
      }
      public Builder setLed(boolean value) {
        bitField0_ |= 0x00000002;
        led_ = value;
        onChanged();
        return this;
      }
      public Builder clearLed() {
        bitField0_ = (bitField0_ & ~0x00000002);
        led_ = false;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:nc.niemb.User1Data)
    }
    
    static {
      defaultInstance = new User1Data(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:nc.niemb.User1Data)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_nc_niemb_User1Data_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nc_niemb_User1Data_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013niemb.proto\022\010nc.niemb\"(\n\tUser1Data\022\016\n\006" +
      "switch\030\001 \001(\010\022\013\n\003led\030\002 \001(\010"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_nc_niemb_User1Data_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_nc_niemb_User1Data_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_nc_niemb_User1Data_descriptor,
              new java.lang.String[] { "Switch", "Led", },
              nc.niemb.Niemb.User1Data.class,
              nc.niemb.Niemb.User1Data.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
